#!/bin/bash
# we want to run an npm command to build into the build directory
# the HOME directory isn't writeable so we need to temporarily change
# the directory, run the build and then change back to the original

# save the initial $HOME
INITIAL_HOME=$HOME

# the $OPENSHIFT_REPO_DIR is where everything is kept and is writeable
# switch to this directory and make it the current $HOME
cd $OPENSHIFT_REPO_DIR
export HOME=$OPENSHIFT_REPO_DIR

# run the build script
echo "Starting 'npm run build'..."
npm run build

# switch $HOME back to the initial value
export HOME=$INITIAL_HOME
echo "HOME is now $HOME"
